site_name: MERN Web Technologies
theme:
  name: material
nav:
  - Home: index.md
  - Web Foundations:
      - Overview: 01-web-foundations/overview.md
  - Slides: slides/index.md

markdown_extensions:
  - fenced_code
  - codehilite

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - assets/javascripts/mermaid-init.js
