
site_name: MERN Web Technologies
theme:
  name: material
nav:
  - Home: index.md
  - Web Foundations:
      - Overview: 01-web-foundations/overview.md
  - Node & Express:
      - Overview: 02-node-express/overview.md
  - React:
      - Overview: 03-react/overview.md
